# This is a basic workflow to help you get started with Actions

name: Build, Publish, FTP Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  release:
    types: [publish]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./WebCalToHtml/WebCalToHtml.sln
    - name: Build
      run: dotnet build ./WebCalToHtml/WebCalToHtml.sln --configuration Release --no-restore 
    - name: Test
      run: dotnet test ./WebCalToHtml/WebCalToHtml.sln --no-restore --verbosity normal

  FTP-Deploy-Action:
    needs: [build]
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
