name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore .\WebCalToHtml\WebCalToHtml.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore .\WebCalToHtml\WebCalToHtml.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal .\WebCalToHtml\WebCalToHtml.sln
